ingress:
  enabled: true
  className: ''
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/connection-proxy-header: keep-alive
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '600'
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: '600'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '600'
    nginx.ingress.kubernetes.io/whitelist-source-range: 78.130.149.162/32, 31.13.239.28/32, 31.13.239.29/32, 31.13.239.30/3
  hosts:
    - host: domovoy2.thepineslab.net # add later
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: domovoy2 
              port:
                number: service.port

  tls:
    - secretName: domovoy2 
      hosts:
        - domovoy2.thepineslab.net

# configMap:
#   enabled: true
#   data:
